### ISSUE TITLE
Invalid byte sequence in US-ASCII(ArgumentError)

### ISSUE THREAD

**Issue by lcasassa** [treasure-data/embulk-input-zendesk#45]
Hi, what can I do to solve this issue?

```2018-03-21 17:22:32.063 +0000 [DEBUG] (0032:task-0000): Fetching https://buda.zendesk.com/api/v2/incremental/tickets.json
2018-03-21 17:22:32.090 +0000 [DEBUG] (0032:task-0000): org/jruby/RubyRegexp.java:1078:in `==='
2018-03-21 17:22:32.090 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient/jruby_ssl_socket.rb:343:in `block in add'
2018-03-21 17:22:32.091 +0000 [DEBUG] (0032:task-0000): org/jruby/RubyString.java:4961:in `each_line'
2018-03-21 17:22:32.091 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient/jruby_ssl_socket.rb:342:in `add'
2018-03-21 17:22:32.092 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient/jruby_ssl_socket.rb:531:in `block in create_ssl_context'
2018-03-21 17:22:32.092 +0000 [DEBUG] (0032:task-0000): org/jruby/RubyArray.java:1735:in `each'
2018-03-21 17:22:32.092 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient/jruby_ssl_socket.rb:530:in `create_ssl_context'
2018-03-21 17:22:32.092 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient/jruby_ssl_socket.rb:547:in `create_ssl_socket'
2018-03-21 17:22:32.092 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient/jruby_ssl_socket.rb:485:in `initialize'
2018-03-21 17:22:32.092 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient/jruby_ssl_socket.rb:474:in `create_socket'
2018-03-21 17:22:32.092 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient/session.rb:752:in `block in connect'
2018-03-21 17:22:32.092 +0000 [DEBUG] (0032:task-0000): org/jruby/ext/timeout/Timeout.java:149:in `timeout'
2018-03-21 17:22:32.093 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
2018-03-21 17:22:32.093 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
2018-03-21 17:22:32.093 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
2018-03-21 17:22:32.093 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
2018-03-21 17:22:32.093 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
2018-03-21 17:22:32.093 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
2018-03-21 17:22:32.093 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
2018-03-21 17:22:32.093 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
2018-03-21 17:22:32.093 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/httpclient-2.8.3/lib/httpclient.rb:743:in `get'
2018-03-21 17:22:32.093 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/embulk-input-zendesk-0.2.6/lib/embulk/input/zendesk/client.rb:279:in `block in request'
2018-03-21 17:22:32.093 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/perfect_retry-0.5.0/lib/perfect_retry.rb:115:in `block in retry_with_catch'
2018-03-21 17:22:32.093 +0000 [DEBUG] (0032:task-0000): org/jruby/RubyKernel.java:1114:in `catch'
2018-03-21 17:22:32.093 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/perfect_retry-0.5.0/lib/perfect_retry.rb:114:in `block in retry_with_catch'
2018-03-21 17:22:32.093 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/perfect_retry-0.5.0/lib/perfect_retry.rb:113:in `retry_with_catch'
2018-03-21 17:22:32.093 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/perfect_retry-0.5.0/lib/perfect_retry.rb:72:in `with_retry'
2018-03-21 17:22:32.094 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/embulk-input-zendesk-0.2.6/lib/embulk/input/zendesk/client.rb:277:in `request'
2018-03-21 17:22:32.094 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/embulk-input-zendesk-0.2.6/lib/embulk/input/zendesk/client.rb:192:in `block in incremental_export'
2018-03-21 17:22:32.094 +0000 [DEBUG] (0032:task-0000): org/jruby/RubyKernel.java:1292:in `loop'
2018-03-21 17:22:32.094 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/embulk-input-zendesk-0.2.6/lib/embulk/input/zendesk/client.rb:190:in `incremental_export'
2018-03-21 17:22:32.094 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/embulk-input-zendesk-0.2.6/lib/embulk/input/zendesk/client.rb:75:in `block in tickets'
2018-03-21 17:22:32.094 +0000 [DEBUG] (0032:task-0000): org/jruby/RubyKernel.java:1806:in `public_send'
2018-03-21 17:22:32.094 +0000 [DEBUG] (0032:task-0000): /root/.embulk/lib/gems/gems/embulk-input-zendesk-0.2.6/lib/embulk/input/zendesk/plugin.rb:115:in `run'
2018-03-21 17:22:32.094 +0000 [DEBUG] (0032:task-0000): uri:classloader:/gems/embulk-0.9.4-java/lib/embulk/input_plugin.rb:107:in `run'
2018-03-21 17:22:32.095 +0000 [WARN] (0032:task-0000): [3/5] Retrying after 16 seconds. Ocurred: invalid byte sequence in US-ASCII(ArgumentError)
```

Thanks

**Comment by tvhung83** [comment]
hi @lcasassa , thank you for letting us know, I will take a look at this.

**Comment by tvhung83** [comment]
@lcasassa your stack trace seems to be incomplete, what I need to investigate is the stack trace after last line. Would you be able to provide another stack trace?
In the mean time, what I can say is that it could be a locale issue of Ruby docker. Can you try to add `-e LANG=C.UTF-8` when you run it, for ex: `docker run --rm -it -e LANG=C.UTF-8 ruby:2.4.0 bash`?
